using System;

namespace DevBlah.DapperOrm.Helper.Attributes
{
    /// <summary>
    /// Attribute to specify your primary key of your entity
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public class KeyAttribute : Attribute
    {
        /// <summary>
        /// default setting for auto incremented primary key
        /// </summary>
        private bool _isAutoGenerated = true;

        /// <summary>
        /// Specifies, if the key is incremented automatically
        /// </summary>
        public bool IsAutoGenerated
        {
            get { return _isAutoGenerated; }
            set { _isAutoGenerated = value; }
        }
    }
}