using System;

namespace DevBlah.DapperOrm.Helper.Attributes
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    public class KeyAttribute : Attribute
    {
        private bool _isAutoGenerated = true;

        /// <summary>
        /// Gibt an, ob der Key automatisch inkrementiert wird
        /// </summary>
        public bool IsAutoGenerated
        {
            get { return _isAutoGenerated; }
            set { _isAutoGenerated = value; }
        }
    }
}